config/routes.rb
NewzuppCrawler::Application.routes.draw do
  constraints(:host => "www.newzupp.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "newzupp.com" }.to_s
    }
  end
  root :to => "stories#home"

  match "/digg" => "stories#digg"

  match "/reddit" => "stories#reddit"

  match "/tweetmeme" => "stories#tweetmeme"

  match "/hackernews" => "stories#hackernews"

  match "/stats" => "info#stats"

  match "/about" => "info#about"

  match "/roadmap" => "info#roadmap"

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout  

end

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-container">
    <div class="footer-details">
      <p><%= link_to "Stats", stats_path %> | <%= link_to "Roadmap", roadmap_path%> | <a href="https://github.com/jagira/newzupp" target="blank">Source</a> |
      <%= link_to "About", about_path %></p>
    </div>
    <p>Created by <a href="http://jigarpatel.in" target="blank">Jigar Patel</a> - <a href="http://twitter.com/jagira" target="blank">Twitter</a> | <a href="mailto:jagira@gmail.com">Mail</a></p>
  <br/>
  <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fnewzupp.com&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;font=verdana&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
  </div>
</div>

<!--<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
  <script type="text/javascript">//<![CDATA[_uacct = "UA-1876445-3"; urchinTracker();//]]>
</script>-->

<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=5699771;
var sc_invisible=1;
var sc_security="86c7ca22";
</script>

<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="counter for tumblr"
href="http://statcounter.com/tumblr/" target="_blank"><img
class="statcounter"
src="http://c.statcounter.com/5699771/0/86c7ca22/1/"
alt="counter for tumblr" ></a></div></noscript>
<!-- End of StatCounter Code -->

app/views/shared/_header.html.erb
<div class="header">

   <div class="header-container">

     <h2><a href="/">Newzupp</a></h2>

     <div class="nav">
       <div class="site-link">
         <%= link_to "Tweetmeme", tweetmeme_path %>
       </div>

       <div class="site-link">
         <%= link_to "Digg", digg_path %>
       </div>

       <div class="site-link">
         <%= link_to "Reddit", reddit_path %>
       </div>

       <div class="site-link">
         <%= link_to "HackerNews", hackernews_path %>
       </div>

       <div class="site-link">
         <%= link_to "Home", root_path %>
       </div>

    </div>

</div>